{{/*
=============================================================================
ClusterSecretStore
=============================================================================
Defines the ClusterSecretStore connecting to the cloud provider's secret
manager backend.
=============================================================================
*/}}
{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/{{ .Values.eso.version }}
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.clusterSecretStore.name }}
    app.kubernetes.io/part-of: {{ .Values.projectName }}
    app.kubernetes.io/managed-by: helm
spec:
  provider:
{{- if eq .Values.provider "gcp" }}
    gcpsm:
      projectID: {{ .Values.providerConfig.gcpsm.projectID }}
{{- else if eq .Values.provider "aws" }}
    aws:
      service: {{ .Values.providerConfig.aws.service }}
      region: {{ .Values.providerConfig.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
{{- else if eq .Values.provider "azure" }}
    azurekv:
      vaultUrl: {{ .Values.providerConfig.azurekv.vaultUrl }}
      authType: ManagedIdentity
{{- end }}
{{- end }}
