apiVersion: v1
kind: Service
metadata:
  name: hasura
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hasura.service.type }}
  ports:
    - port: {{ .Values.hasura.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "hasura.selectorLabels" . | nindent 4 }}
