apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.projectName }}-kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: {{ .Values.projectName }}
    app.kubernetes.io/managed-by: ironplate
