apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ .Release.Name }}-dapr-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  mtls:
    enabled: {{ .Values.mtls.enabled }}
{{- if .Values.observability.enabled }}
  tracing:
    samplingRate: {{ .Values.tracing.samplingRate | quote }}
    otel:
      endpointAddress: {{ .Values.tracing.otel.endpoint | quote }}
      isSecure: {{ .Values.tracing.otel.isSecure }}
      protocol: {{ .Values.tracing.otel.protocol | quote }}
{{- else }}
  tracing:
    samplingRate: "0"
{{- end }}
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
