{{- if .Values.redis.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.statestore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.statestore.type }}
  version: {{ .Values.statestore.version }}
  metadata:
    - name: redisHost
      value: {{ .Values.statestore.metadata.redisHost | quote }}
    - name: redisPassword
      value: {{ .Values.statestore.metadata.redisPassword | quote }}
    - name: actorStateStore
      value: "true"
{{- else }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.statestore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.statestore.type }}
  version: {{ .Values.statestore.version }}
  metadata: []
{{- end }}
