apiVersion: v1
kind: Service
metadata:
  name: langfuse
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.langfuse.service.type }}
  ports:
    - port: {{ .Values.langfuse.service.port }}
      targetPort: {{ .Values.langfuse.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "langfuse.selectorLabels" . | nindent 4 }}
